---
title: "AC_Distribution Fitting"
author: "Srijan Kundu"
date: "2022-11-30"
output: pdf_document
---

# Normal Distribution:

---
```{r}
library(matlib)
library(pracma)
```



## Question:


## Answer:

```{r}
class_int <- seq(70, 140, 10)
class <- c("70-80", "80-90", "90-100", "100-110", "110-120", "120-130", "130-140")
f <- c(22, 48, 72, 104, 86, 49, 30)
x <- seq(75, 135, 10)
```

```{r}
x_bar <- dot(f, x)/(sum(f))
x_bar
st_var <- sum(((x - x_bar)**2)*f)/(sum(f) - 1)
st_var
st_dev <- sqrt(st_var)
```

Here, $\hat{\mu} = 105.97, \hat{\sigma^2} = 246.37$.

```{r}
p <- c((pnorm(80, x_bar, st_dev)-pnorm(70, x_bar, st_dev)), 
       (pnorm(90, x_bar, st_dev)-pnorm(80, x_bar, st_dev)),
       (pnorm(100, x_bar, st_dev)-pnorm(90, x_bar, st_dev)), 
       (pnorm(110, x_bar, st_dev)-pnorm(100, x_bar, st_dev)),
       (pnorm(120, x_bar, st_dev)-pnorm(110, x_bar, st_dev)),
       (pnorm(130, x_bar, st_dev)-pnorm(120, x_bar, st_dev)),
       (pnorm(140, x_bar, st_dev)-pnorm(130, x_bar, st_dev)))
p
```

Expected frequency:
```{r}
exp_freq <- p*sum(f)
exp_freq
```

Goodness of fit:
```{r}
df <- data.frame(class, f, exp_freq, p)
colnames(df) <- c("Class_Intervals", "Observed_Frequency", "Expected_Frequency", "Probability")
df
#Chi-square test statistic
#df = (k-1-r) = (7-1-2) = 4; k = no. of obs, r = no. of parameters
chi <- (f - exp_freq)**2/exp_freq
sum(chi)
qchisq(0.95, 4)
```


