---
title: 'Non Central Chi Square'
author: "Srijan Kundu"
date: "2022-11-29"
output: pdf_document
---

```{r}
library(ggpubr)
library(dplyr)
set.seed(423)
```


---

```{r}
n1 <- c(2, 7, 9 ,13, 15)
l <- c(0, 5, 7, 8, 12)
n2 <- c(3, 5, 9, 14, 22)
```


```{r}
#for df1 fixed as 2
data11 <- rf(1000, n1[1], n2[1], l[1])
data12 <- rf(1000, n1[1], n2[2], l[1])
data13 <- rf(1000, n1[1], n2[3], l[1])
data14 <- rf(1000, n1[1], n2[4], l[1])
data15 <- rf(1000, n1[1], n2[5], l[1])
  
p11 <- ggplot(NULL, aes(x = data11)) + geom_histogram(aes(y = ..density..)) + geom_density()
p12 <- ggplot(NULL, aes(x = data12)) + geom_histogram(aes(y = ..density..)) + geom_density()
p13 <- ggplot(NULL, aes(x = data13)) + geom_histogram(aes(y = ..density..)) + geom_density()
p14 <- ggplot(NULL, aes(x = data14)) + geom_histogram(aes(y = ..density..)) + geom_density()
p15 <- ggplot(NULL, aes(x = data15)) + geom_histogram(aes(y = ..density..)) + geom_density()

o1 <- ggarrange(p11, p12, p13, p14, p15, nrow = 1)
o1 <- annotate_figure(o1, top = text_grob("df1 = 2, ncp = 0, df2 varies in (3, 5, 9, 14, 22)", 
               color = "red", face = "bold", size = 14))


data21 <- rf(1000, n1[1], n2[1], l[2])
data22 <- rf(1000, n1[1], n2[2], l[2])
data23 <- rf(1000, n1[1], n2[3], l[2])
data24 <- rf(1000, n1[1], n2[4], l[2])
data25 <- rf(1000, n1[1], n2[5], l[2])
  
p21 <- ggplot(NULL, aes(x = data21)) + geom_histogram(aes(y = ..density..)) + geom_density()
p22 <- ggplot(NULL, aes(x = data22)) + geom_histogram(aes(y = ..density..)) + geom_density()
p23 <- ggplot(NULL, aes(x = data23)) + geom_histogram(aes(y = ..density..)) + geom_density()
p24 <- ggplot(NULL, aes(x = data24)) + geom_histogram(aes(y = ..density..)) + geom_density()
p25 <- ggplot(NULL, aes(x = data25)) + geom_histogram(aes(y = ..density..)) + geom_density()

o2 <-  ggarrange(p21, p22, p23, p24, p25, nrow = 1)
o2 <- annotate_figure(o2, top = text_grob("df1 = 2, ncp = 5, df2 varies in (3, 5, 9, 14, 22)", 
               color = "red", face = "bold", size = 14))


data31 <- rf(1000, n1[1], n2[1], l[3])
data32 <- rf(1000, n1[1], n2[2], l[3])
data33 <- rf(1000, n1[1], n2[3], l[3])
data34 <- rf(1000, n1[1], n2[4], l[3])
data35 <- rf(1000, n1[1], n2[5], l[3])
  
p31 <- ggplot(NULL, aes(x = data31)) + geom_histogram(aes(y = ..density..)) + geom_density()
p32 <- ggplot(NULL, aes(x = data32)) + geom_histogram(aes(y = ..density..)) + geom_density()
p33 <- ggplot(NULL, aes(x = data33)) + geom_histogram(aes(y = ..density..)) + geom_density()
p34 <- ggplot(NULL, aes(x = data34)) + geom_histogram(aes(y = ..density..)) + geom_density()
p35 <- ggplot(NULL, aes(x = data35)) + geom_histogram(aes(y = ..density..)) + geom_density()

o3 <-  ggarrange(p31, p32, p33, p34, p35, nrow = 1)
o3 <- annotate_figure(o3, top = text_grob("df1 = 2, ncp = 7, df2 varies in (3, 5, 9, 14, 22)", 
               color = "red", face = "bold", size = 14))


data41 <- rf(1000, n1[1], n2[1], l[4])
data42 <- rf(1000, n1[1], n2[2], l[4])
data43 <- rf(1000, n1[1], n2[3], l[4])
data44 <- rf(1000, n1[1], n2[4], l[4])
data45 <- rf(1000, n1[1], n2[5], l[4])
  
p41 <- ggplot(NULL, aes(x = data41)) + geom_histogram(aes(y = ..density..)) + geom_density()
p42 <- ggplot(NULL, aes(x = data42)) + geom_histogram(aes(y = ..density..)) + geom_density()
p43 <- ggplot(NULL, aes(x = data43)) + geom_histogram(aes(y = ..density..)) + geom_density()
p44 <- ggplot(NULL, aes(x = data44)) + geom_histogram(aes(y = ..density..)) + geom_density()
p45 <- ggplot(NULL, aes(x = data45)) + geom_histogram(aes(y = ..density..)) + geom_density()

o4 <- ggarrange(p41, p42, p43, p44, p45, nrow = 1)
o4 <- annotate_figure(o4, top = text_grob("df1 = 2, ncp = 8, df2 varies in (3, 5, 9, 14, 22)", 
               color = "red", face = "bold", size = 14))


data51 <- rf(1000, n1[1], n2[1], l[5])
data52 <- rf(1000, n1[1], n2[2], l[5])
data53 <- rf(1000, n1[1], n2[3], l[5])
data54 <- rf(1000, n1[1], n2[4], l[5])
data55 <- rf(1000, n1[1], n2[5], l[5])
  
p51 <- ggplot(NULL, aes(x = data51)) + geom_histogram(aes(y = ..density..)) + geom_density()
p52 <- ggplot(NULL, aes(x = data52)) + geom_histogram(aes(y = ..density..)) + geom_density()
p53 <- ggplot(NULL, aes(x = data53)) + geom_histogram(aes(y = ..density..)) + geom_density()
p54 <- ggplot(NULL, aes(x = data54)) + geom_histogram(aes(y = ..density..)) + geom_density()
p55 <- ggplot(NULL, aes(x = data55)) + geom_histogram(aes(y = ..density..)) + geom_density()

o5 <- ggarrange(p51, p52, p53, p54, p55, nrow = 1)
o5 <- annotate_figure(o5, top = text_grob("df1 = 2, ncp = 12, df2 varies in (3, 5, 9, 14, 22)", 
               color = "red", face = "bold", size = 14))


ggarrange(o1, o2, o3, o4, o5, nrow = 5)
```

```{r}
#for df1 fixed as 7
data61 <- rf(1000, n1[2], n2[1], l[1])
data62 <- rf(1000, n1[2], n2[2], l[1])
data63 <- rf(1000, n1[2], n2[3], l[1])
data64 <- rf(1000, n1[2], n2[4], l[1])
data65 <- rf(1000, n1[2], n2[5], l[1])
  
p61 <- ggplot(NULL, aes(x = data61)) + geom_histogram(aes(y = ..density..)) + geom_density()
p62 <- ggplot(NULL, aes(x = data62)) + geom_histogram(aes(y = ..density..)) + geom_density()
p63 <- ggplot(NULL, aes(x = data63)) + geom_histogram(aes(y = ..density..)) + geom_density()
p64 <- ggplot(NULL, aes(x = data64)) + geom_histogram(aes(y = ..density..)) + geom_density()
p65 <- ggplot(NULL, aes(x = data65)) + geom_histogram(aes(y = ..density..)) + geom_density()

o6 <- ggarrange(p61, p62, p63, p64, p65, nrow = 1)
o6 <- annotate_figure(o6, top = text_grob("df1 = 7, ncp = 0, df2 varies in (3, 5, 9, 14, 22)", 
               color = "red", face = "bold", size = 14))


data71 <- rf(1000, n1[2], n2[1], l[2])
data72 <- rf(1000, n1[2], n2[2], l[2])
data73 <- rf(1000, n1[2], n2[3], l[2])
data74 <- rf(1000, n1[2], n2[4], l[2])
data75 <- rf(1000, n1[2], n2[5], l[2])
  
p71 <- ggplot(NULL, aes(x = data71)) + geom_histogram(aes(y = ..density..)) + geom_density()
p72 <- ggplot(NULL, aes(x = data72)) + geom_histogram(aes(y = ..density..)) + geom_density()
p73 <- ggplot(NULL, aes(x = data73)) + geom_histogram(aes(y = ..density..)) + geom_density()
p74 <- ggplot(NULL, aes(x = data74)) + geom_histogram(aes(y = ..density..)) + geom_density()
p75 <- ggplot(NULL, aes(x = data75)) + geom_histogram(aes(y = ..density..)) + geom_density()

o7 <-  ggarrange(p71, p72, p73, p74, p75, nrow = 1)
o7 <- annotate_figure(o7, top = text_grob("df1 = 7, ncp = 5, df2 varies in (3, 5, 9, 14, 22)", 
               color = "red", face = "bold", size = 14))


data81 <- rf(1000, n1[2], n2[1], l[3])
data82 <- rf(1000, n1[2], n2[2], l[3])
data83 <- rf(1000, n1[2], n2[3], l[3])
data84 <- rf(1000, n1[2], n2[4], l[3])
data85 <- rf(1000, n1[2], n2[5], l[3])
  
p81 <- ggplot(NULL, aes(x = data81)) + geom_histogram(aes(y = ..density..)) + geom_density()
p82 <- ggplot(NULL, aes(x = data82)) + geom_histogram(aes(y = ..density..)) + geom_density()
p83 <- ggplot(NULL, aes(x = data83)) + geom_histogram(aes(y = ..density..)) + geom_density()
p84 <- ggplot(NULL, aes(x = data84)) + geom_histogram(aes(y = ..density..)) + geom_density()
p85 <- ggplot(NULL, aes(x = data85)) + geom_histogram(aes(y = ..density..)) + geom_density()

o8 <-  ggarrange(p81, p82, p83, p84, p85, nrow = 1)
o8 <- annotate_figure(o8, top = text_grob("df1 = 7, ncp = 7, df2 varies in (3, 5, 9, 14, 22)", 
               color = "red", face = "bold", size = 14))


data91 <- rf(1000, n1[2], n2[1], l[4])
data92 <- rf(1000, n1[2], n2[2], l[4])
data93 <- rf(1000, n1[2], n2[3], l[4])
data94 <- rf(1000, n1[2], n2[4], l[4])
data95 <- rf(1000, n1[2], n2[5], l[4])
  
p91 <- ggplot(NULL, aes(x = data91)) + geom_histogram(aes(y = ..density..)) + geom_density()
p92 <- ggplot(NULL, aes(x = data92)) + geom_histogram(aes(y = ..density..)) + geom_density()
p93 <- ggplot(NULL, aes(x = data93)) + geom_histogram(aes(y = ..density..)) + geom_density()
p94 <- ggplot(NULL, aes(x = data94)) + geom_histogram(aes(y = ..density..)) + geom_density()
p95 <- ggplot(NULL, aes(x = data95)) + geom_histogram(aes(y = ..density..)) + geom_density()

o9 <- ggarrange(p91, p92, p93, p94, p95, nrow = 1)
o9 <- annotate_figure(o9, top = text_grob("df1 = 7, ncp = 8, df2 varies in (3, 5, 9, 14, 22)", 
               color = "red", face = "bold", size = 14))


data101 <- rf(1000, n1[2], n2[1], l[5])
data102 <- rf(1000, n1[2], n2[2], l[5])
data103 <- rf(1000, n1[2], n2[3], l[5])
data104 <- rf(1000, n1[2], n2[4], l[5])
data105 <- rf(1000, n1[2], n2[5], l[5])
  
p101 <- ggplot(NULL, aes(x = data101)) + geom_histogram(aes(y = ..density..)) + geom_density()
p102 <- ggplot(NULL, aes(x = data102)) + geom_histogram(aes(y = ..density..)) + geom_density()
p103 <- ggplot(NULL, aes(x = data103)) + geom_histogram(aes(y = ..density..)) + geom_density()
p104 <- ggplot(NULL, aes(x = data104)) + geom_histogram(aes(y = ..density..)) + geom_density()
p105 <- ggplot(NULL, aes(x = data105)) + geom_histogram(aes(y = ..density..)) + geom_density()

o10 <- ggarrange(p101, p102, p103, p104, p105, nrow = 1)
o10 <- annotate_figure(o10, top = text_grob("df1 = 7, ncp = 12, df2 varies in (3, 5, 9, 14, 22)", 
               color = "red", face = "bold", size = 14))


ggarrange(o6, o7, o8, o9, o10, nrow = 5)
```


